name = "culturalentomology"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# next-on-pages output configuration
pages_build_output_dir = ".vercel/output/static"

[vars]
# Environment variables for Cloudflare Pages
NEXT_PUBLIC_CF_IMAGES_ACCOUNT = "8HA2zssW7KVTY84RTNfJgA"

